language: python
os:
  - linux
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
    - pip install "virtualenv<14.0.0" -e .[testsuite]
script:
    - nosetests -v -d --with-coverage --cover-package=beaker
